//
// Translated by CS2J (http://www.cs2j.com): 24.08.2018 23:51:08
//

package Book2Chart.GUI.Properties;

import Book2Chart.GUI.Properties.Settings;


//------------------------------------------------------------------------------// <auto-generated>//     Dieser Code wurde von einem Tool generiert.//     Laufzeitversion:4.0.30319.17626////     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn//     der Code erneut generiert wird.// </auto-generated>//------------------------------------------------------------------------------
public final class Settings  extends System.Configuration.ApplicationSettingsBase 
{

    private static Settings defaultInstance = ((Settings)(/* [UNSUPPORTED] external aliases are not yet supported "global::System" */.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
    public static Settings getDefault() throws Exception {
        return defaultInstance;
    }

}


