////
//// Translated by CS2J (http://www.cs2j.com): 24.08.2018 23:51:08
////
//
//package de.debuglevel.book2graph.gui.Properties
//
//import de.debuglevel.book2graph.gui.Properties.Resources
//
////------------------------------------------------------------------------------
//// <auto-generated>
////     Dieser Code wurde von einem Tool generiert.
////     Laufzeitversion:4.0.30319.17626
////
////     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
////     der Code erneut generiert wird.
//// </auto-generated>
////------------------------------------------------------------------------------
///**
// * Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
// */
//// Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
//// -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
//// Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
//// mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
//class Resources @Throws(Exception::class)
//constructor() {
//    companion object {
//        private var resourceMan = System.Resources.ResourceManager()
//        /**
//         * Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
//         * Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
//         */
//        var culture = System.Globalization.CultureInfo()
//
//        /**
//         * Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
//         */
//        val resourceManager: System.Resources.ResourceManager
//            @Throws(Exception::class)
//            get() {
//                if (Object.ReferenceEquals(resourceMan, null)) {
//                    val temp = System.Resources.ResourceManager("de.debuglevel.book2graph.gui.Properties.Resources", Resources::class.java.Assembly)
//                    resourceMan = temp
//                }
//
//                return resourceMan
//            }
//    }
//
//}
//
//
