//
// Translated by CS2J (http://www.cs2j.com): 24.08.2018 23:51:08
//

package Book2Chart.GUI.Properties;

import Book2Chart.GUI.Properties.Resources;

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17626
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
/**
* Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
*/
// Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
// -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
// Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
// mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
public class Resources   
{
    private static System.Resources.ResourceManager resourceMan = new System.Resources.ResourceManager();
    private static System.Globalization.CultureInfo resourceCulture = new System.Globalization.CultureInfo();
    public Resources() throws Exception {
    }

    /**
    * Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    */
    public static System.Resources.ResourceManager getResourceManager() throws Exception {
        if (Object.ReferenceEquals(resourceMan, null))
        {
            System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Book2Chart.GUI.Properties.Resources", Resources.class.Assembly);
            resourceMan = temp;
        }
         
        return resourceMan;
    }

    /**
    * Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    * Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    */
    public static System.Globalization.CultureInfo getCulture() throws Exception {
        return resourceCulture;
    }

    public static void setCulture(System.Globalization.CultureInfo value) throws Exception {
        resourceCulture = value;
    }

}


